DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS result;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nickname TEXT NOT NULL,
  age INTEGER,
  gender TEXT
);

CREATE TABLE session (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user1_id INTEGER NOT NULL,
  user2_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user1_id) REFERENCES user (id),
  FOREIGN KEY (user2_id) REFERENCES user (id)
);

CREATE TABLE result (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id INTEGER NOT NULL,
  score INTEGER NOT NULL,
  data_path TEXT,
  FOREIGN KEY (session_id) REFERENCES session (id)
);
